# Базові значення
BASE_HP = 100
BASE_STAMINA = 100
BASE_MANA = 50

# Множники атрибутів
STRENGTH_DAMAGE_MULTIPLIER = 1.5
STRENGTH_HP_MULTIPLIER = 2.0
INTELLIGENCE_MANA_MULTIPLIER = 2.0
INTELLIGENCE_DAMAGE_MULTIPLIER = 2.0

# Шанси
BASE_CRIT_CHANCE = 0.05
BASE_DODGE_CHANCE = 0.10
AGILITY_CRIT_BONUS = 0.005
AGILITY_DODGE_BONUS = 0.01
LUCK_BONUS_MULTIPLIER = 0.003

# Конфігурація гри
DIFFICULTY = "NORMAL"  # EASY, NORMAL, HARD
AUTO_SAVE = True
SAVE_INTERVAL = 5  # кожні 5 ходів